### ISSUE TITLE
Create Develop Enviroment

### ISSUE THREAD

**Issue by monkeydaichan** [asbloom-py/flutter-study#1]
https://www.youtube.com/watch?v=kpvVENfDCRc&list=PLuLRJz1UnJzE4-HlkLTG8ARbZ2TDBNHzZ

**Comment by KyoheiTaniguchi** [comment]
@monkeydaichan 
1.Pathを通したい
2.vim .bash_profileを入力すると表示が変更される(文字列が出現する)
3. E325: atencion........と表示されて動画のように進めない

**Comment by monkeydaichan** [comment]
> @monkeydaichan 1.Pathを通したい 2.vim .bash_profileを入力すると表示が変更される(文字列が出現する) 3. E325: atencion........と表示されて動画のように進めない

エラー文言で一度検索してみる.  
.swpファイルが存在しているということは,別のプログラムかソフトが同じファイルを開いているため,編集ができない状態.  
.swpファイルを消せば解決

**Comment by KyoheiTaniguchi** [comment]
.zshrc
bashは古いからパスを通すためには上のものを使う

**Comment by TakuroNagasawa** [comment]
シェルがzshではなかったので、パスが通らなかった。
ターミナルの環境設定から、シェルを変更。
sh -> zsh へ
<img width="665" alt="スクリーンショット 2022-03-02 19 51 29" src="https://user-images.githubusercontent.com/53826762/156463134-2bbac045-8adf-4a16-99d9-39844852e23a.png">

**Comment by monkeydaichan** [comment]
`~/.zshrc`

```
#flutterをインストールしたパス
export PATH="$PATH:/Users/daichi/Library/flutter/bin"
```
